export const footerStructuredData = {
  "@context": "https://schema.org",
  "@type": "Restaurant",
  name: "میزنکس",
  alternateName: "Miznex",
  description: "برند متفاوت در دنیای منو کافه و رستوران با کیفیت، طراحی مدرن",
  // url: "https://miznexo.vercel.app",
  telephone: "+98-21-12345678",
  email: "info@miznex.ir",
  address: {
    "@type": "PostalAddress",
    streetAddress: "خیابان ولیعصر، پلاک ۱۲۳",
    addressLocality: "تهران",
    addressCountry: "IR",
    postalCode: "12345",
  },
  geo: {
    "@type": "GeoCoordinates",
    latitude: 35.6892,
    longitude: 51.389,
  },
  openingHours: ["Mo-Su 09:00-18:00", "Tu 10:00-17:00", "Th-Fr 09:00-17:00"],

  servesCuisine: ["کافه", "رستوران", "فست فود"],
  priceRange: "$$",
  acceptsReservations: true,
  hasMenu: "https://miznexo.vercel.app/menu",
  sameAs: [
    "https://facebook.com/miznex",
    "https://instagram.com/miznex",
    "https://twitter.com/miznex",
    "https://youtube.com/miznex",
    "https://t.me/miznex",
  ],
};
